
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - YANDEX_ACCESS_KEY=${YANDEX_ACCESS_KEY}
      - db_user=${db_user}
      - db_pass=${db_pass}
      - DB_HOST=postgres
    depends_on:
      - postgres
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: queries
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      postgres -c shared_buffers=256MB
               -c max_connections=20
               -c effective_cache_size=512MB
               -c work_mem=4MB
               -c maintenance_work_mem=64MB
    restart: always
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - backend
    restart: always
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false